apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: safeguard
webhooks:
  - name: safeguard.jw-s.com
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - DELETE
        resources:
          - "*"
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: kube-system
        name: safeguard
        path: '/protected'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxRENDQWJ5Z0F3SUJBZ0lSQUlNZDRIa3NyaXRDY3M5NzkwS2QxUXN3RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQ2hNSWQyaHBkSFJxYjJVd0hoY05NVGN3TkRJMU1EZ3pPREF3V2hjTk1qQXdOREE1TURnegpPREF3V2pBVE1SRXdEd1lEVlFRS0V3aDNhR2wwZEdwdlpUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFPMms4OXFmOWlyanhYdmh2YXJadXcxM25VdS8rN2lVd2ptUWtIVmVOY2l2YW5VeS92b0EKRnZzeXo5eG9YZzY5a0NhY213bWcvbWkzT200d0tuV2lOYlBXUkE5cngrcDI2VTNZMFVRVTk1VlNhZnlESzZKdgp2cWg0NFZQRVF2VUZDcWpuemZxNnpkaVM3UXNGcDhuZHUxR01QTkFkUjI5MU9nL1d2UGVyaHV6MUQrUDBHdzA1Clo2ZEFueWowOElpTGNBdERocW9QaDlyai9mYU5FaVdVWFdQVW4xMndNS3ozYzZldTE4bkZ3THBOaTFRRndNNnoKdTUyUDc2R3lIZWxDR2p0dkZkbDFqOHRTdkdiVnNHc1dRSFNsZlFJUWJ6S2VsNlhoaVhKVnZDTUZIdjdraGEyTgp4d2VuL2h5ZUI3VUhLY0c3V3BaTE9wa3YxNDYyTUJ2dVVTVUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFECkFnS3NNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRVBNSGdzNmg1ZWcKYW9JSmpzMm9yb2hoRU44WDNHT2xYcHUvMEJHT2ovVkpwN1h2T3JQK2ZRa0w5VHByWTJiYktmRTFETHY0SWg0YQp1Ly9yd3ljdnNKQzQrT2wwVHhzWTFoNm83NEVxS2trVUltS01DanNoRmZmRWpqUU9jNlgwTEp5REcxWTNkNU40Ckt0N2gvWkpiSWtLZW56UW5XRTY4aklzR1F4MDduN3BNS0FOSVNxMkpKU0JZRlQ1ZVFjbWhheTc5eTJnUVQ2aCsKQjZYWUxsRTFPUEdjT3ROZGg3VGRid3MxdVRFcVVnL2xPbnZjWkg4cGhXbG5kRVQ1M3JMOFR5VVdIUExFYmlWbApZck9qbTA1bkVIcWJDV1Uva25zNmhvcjlYRmh5RFZkK0ZZTU1VempiTnQxeGVNRC92VEhJZUQydVl3UC9GNE9TCm9wdVBVK2I0b2VzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==